version: '3.9'

services:
  postgres:
    image: docker.io/library/postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./storage/postgresql/data:/var/lib/postgresql/data
  redis:
    image: docker.io/library/redis:alpine
    ports:
      - 6379:6379
